//MAIN WEBSITE ACTIONS
export const ADD_A_STORY = 'ADD_A_STORY';
export const GET_USER_STORIES = 'GET_USER_STORIES';

//DASHBOARD ACTIONS
export const APPROVE_STORY = 'APPROVE_STORY';
export const REJECT_STORY = 'REJECT_STORY';
export const DELETE_STORY = 'DELETE_STORY';
export const GET_PENDING_STORIES = 'GET_PENDING_STORIES';